dataset:
  train_percentage: 0.8
  batch_size: 4
  num_workers: 4
  augmentation: True
  width: 512
  height: 512
  subset: 6

train:
  optimizer: "SGD"
  scheduler: "None"
  scheduler_params: 
    step_size: 3
    gamma: 1
  epochs: 10
  lr: 0.001
  weight_decay: 0.0005
  momentum: 0.9
  log_freq: 10
  save_freq: 1
  viz_augmentation: False

model:
  type: 'torchvision'
  name: 'FRCNN'
  freeze: False

metrics:
  metrics: ["IoU", mAP]
  params:
    IoU:
      class_metrics: True
    mAP:
      class_metrics: True
