dataset:
  train_percentage: 0.75
  test_percentage: 0.1
  val_percentage: 0.15
  batch_size: 4
  num_workers: 4
  augmentation: True
  width: 512
  height: 512
  subset: 6

train:
  optimizer: "SGD"
  scheduler: "None"
  scheduler_params: 
    step_size: 15
    gamma: 0.1
  epochs: 100
  lr: 0.0005
  weight_decay: 0.000
  momentum: 0.9
  nesterov: True
  log_freq: 10
  save_freq: 1
  viz_augmentation: False

model:
  type: 'torchvision'
  name: 'SSD'
  freeze: True

metrics:
  metrics: ["IoU", mAP]
  params:
    IoU:
      class_metrics: True
    mAP:
      class_metrics: True
